# [Keras + Universal Sentence Encoder = Deep Meter](https://www.dlology.com/blog/keras-meets-universal-sentence-encoder-transfer-learning-for-text-data/) 

This notebook creates an autoencoder using the Universal Sentence Encoder. The autoencoder output is CMUdict syllables. The dataset is that subset of Allison Parrish's Project Gutenberg poetry archive which happens to scan in iambic pentameter.

The notebook is based on Chengwei Zhang's example of wrapping the USE inside a larger tensorflow model saves to a Keras model (without save the USE itself in the TF model).

The Universal Sentence Encoder makes getting sentence level embeddings as easy as it has historically been to lookup the embeddings for individual words. The sentence embeddings can then be trivially used to compute sentence level meaning similarity as well as to enable better performance on downstream classification tasks using less supervised training data.

Since there are 10 one-hot values for 10 sets of 6k syllables, this is "multi-label classification"
Changes for multi-label classification:
sigmoid activation instead of softmax
binary_crossentropy

Text format is tab-separated, 2 columns: first text, second multi-level
array of syllables:


# Getting Started

This section sets up the environment for access to the Universal Sentence Encoder on TF Hub and provides examples of applying the encoder to words, sentences, and paragraphs.

In [0]:
# Install the latest Tensorflow version.
!pip3 install --quiet "tensorflow>=1.7"
# Install TF-Hub.
!pip3 install --quiet tensorflow-hub
%cd /content
!git clone https://github.com/LanceNorskog/deep_meter || true
%cd deep_meter
!git pull
# could not figure out how to read gzipped files as text!
!gunzip -qf blobs/*.gz || true
!gunzip -qf prepped_data/*.gz || true

/content
fatal: destination path 'deep_meter' already exists and is not an empty directory.
/content/deep_meter
Already up to date.
gzip: blobs/*.gz: No such file or directory


In [2]:
# boilerplate from base notebook
import tensorflow as tf
import tensorflow_hub as hub
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import re
import seaborn as sns
import keras.layers as layers
from keras.models import Model
from keras import backend as K
np.random.seed(10)

Using TensorFlow backend.


In [0]:
# github deep_meter code
import utils
# should not need this to use utils.flatten but is true anyway?
from itertools import chain
import subprocess
import syllables
# misc for this notebook
from ast import literal_eval

import scipy



In [0]:
module_url = "https://tfhub.dev/google/universal-sentence-encoder-large/3" #@param ["https://tfhub.dev/google/universal-sentence-encoder/2", "https://tfhub.dev/google/universal-sentence-encoder-large/3"]

In [5]:
# Import the Universal Sentence Encoder's TF Hub module
embed = hub.Module(module_url)
embed_size = embed.get_output_info_dict()['default'].get_shape()[1].value

INFO:tensorflow:Using /tmp/tfhub_modules to cache modules.


In [0]:
#sentence_labels = utils.flatten([['AE N D'], ['S T AH', 'B ER N'], ['B R AE S'], ['AE N D'], ['T IH N'], ['AE N D'], ['S AA', 'L AH D'], ['G OW L D']])
#other_sentence = utils.flatten([['T UW'], ['M IY'], ['IH T'], ['F L OW Z'], ['AH'], ['S AH', 'L AH N'], ['S T R IY M'], ['AH V'], ['T EH R Z']])
#third_sentence = utils.flatten([['DH AH'], ['N OW', 'B AH L'], ['S IY', 'M AH N'], ['HH UW'], ['W IH TH', 'HH EH L D'], ['DH AH'], ['HH AE N D']])

In [0]:
# read classified poetry lines: text tab [['syll', 'la', 'ble'], ...]
# clip to only most common syllables with syllable manager
def get_data(filename, syll_mgr, num_symbols):
    lines = open(filename, 'r').read().splitlines()
    text_lines = []
    enc_array = []
    num_syllables = syll_mgr.get_size()
    for i in range(0, len(lines)):
      parts = lines[i].split("\t")
      label = utils.flatten(literal_eval(parts[1]))
      if len(label) != num_symbols:
        continue
      enc = np.zeros((num_symbols * syll_mgr.get_size()), dtype=np.int8)
      for j in range(num_symbols):
        enc[num_syllables * j + syll_mgr.get_encoding(label[j])] = 1
      text_lines.append([parts[0]])
      enc_array.append(enc)

    return (np.array(text_lines), np.array(enc_array))


In [0]:
# syllables in descending order of occurrence - 6k in gutenberg.iambic_pentameter, 15k total
# clamp to most common 100 syllables while debugging- use NCE to get all syllables or interesting number
# 98 + pause + wildcard
num_syllables = 1500 
# iambic pentameter
num_symbols = 10
syll_mgr = syllables.syllables(num_syllables)

# slow
num_epochs = 20
adam_0001 = tf.train.AdamOptimizer(0.0000005)

In [0]:
(train_text, train_label) = get_data('prepped_data/gutenberg.iambic_pentameter.train', syll_mgr, num_symbols)
num_training = len(train_text)
#train_text = train_text[0:10000]
#train_label = train_label[0:10000]

(test_text, test_label) = get_data('prepped_data/gutenberg.iambic_pentameter.test', syll_mgr, num_symbols)
num_testing = len(test_text)


In [10]:

for i in range(2):
  print(train_text[i][0])
  print(train_label[i])
  syll_mgr.interpret2(train_label[i])

And stubborn brass, and tin, and solid gold;
[0 0 0 ... 0 0 0]
[7, 38, 343, 0, 7, 0, 7, 77, 78, 114]
['AE N D', 'S T AH', 'B ER N', '?', 'AE N D', '?', 'AE N D', 'S AA', 'L AH D', 'G OW L D']
To me, it flows a sullen stream of tears.
[0 0 0 ... 0 0 0]
[30, 59, 231, 0, 36, 175, 937, 0, 40, 977]
['T UW', 'M IY', 'IH T', '?', 'AH', 'S AH', 'L AH N', '?', 'AH V', 'T EH R Z']


In [11]:
messages = []
for i in range(200):
  messages.append(train_text[i][0])
with tf.Session() as session:
  session.run([tf.global_variables_initializer(), tf.tables_initializer()])
  message_embeddings = session.run(embed(messages))
predicts = message_embeddings

INFO:tensorflow:Saver not created because there are no variables in the graph to restore


In [12]:
predicts = message_embeddings
print(len(predicts))
first = predicts[0]
for i in range(len(predicts) - 1):
  v = predicts[i]
  #print(scipy.spatial.distance.cosine(v, first))

200


## Wrap embed module in a Lambda layer
Explicitly cast the input as a string

In [0]:
def UniversalEmbedding(x):
    return embed(tf.squeeze(tf.cast(x, tf.string)), signature="default", as_dict=True)["default"]


## Assemble model

In [14]:
# changed accuracy from 'choose your own accuracy'
input_text = layers.Input(shape=(1,), dtype=tf.string)
embedding = layers.Lambda(UniversalEmbedding, output_shape=(embed_size,))(input_text)
dense = layers.Dense(1024, activation='relu')(embedding)
pred = layers.Dense(num_syllables * num_symbols, activation='sigmoid')(dense)
model = Model(inputs=[input_text], outputs=pred)
model.compile(loss='binary_crossentropy', optimizer=adam_0001, metrics=['sparse_categorical_accuracy'])
model.summary()

INFO:tensorflow:Saver not created because there are no variables in the graph to restore
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 1)                 0         
_________________________________________________________________
lambda_1 (Lambda)            (None, 512)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 4096)              2101248   
_________________________________________________________________
dense_2 (Dense)              (None, 15000)             61455000  
Total params: 63,556,248
Trainable params: 63,556,248
Non-trainable params: 0
_________________________________________________________________


In [15]:
test_label.shape

(4200, 15000)

In [16]:
print(test_text[200])
syll_mgr.interpret2(test_label[200])

['In this: whatever other blunders lie']
[67, 224, 213, 65, 47, 36, 280, 0, 487, 901]
['IH N', 'DH IH S', 'W AH T', 'EH', 'V ER', 'AH', 'DH ER', '?', 'D ER Z', 'L AY']


## Train Keras model and save weights
This only trains and save our Keras layers not the embed module' weights.

In [17]:
if not os.path.exists('./model.h5'):
  with tf.Session() as session:
    K.set_session(session)
    session.run(tf.global_variables_initializer())
    session.run(tf.tables_initializer())
    history = model.fit(train_text, 
            train_label,
            validation_data=(test_text, test_label),
            epochs=num_epochs,
            batch_size=32)
    model.save_weights('./model.h5')


Train on 58498 samples, validate on 4200 samples
Epoch 1/20
41568/58498 [====================>.........] - ETA: 40s - loss: 0.6926 - sparse_categorical_accuracy: 0.0000e+00

KeyboardInterrupt: ignored

In [143]:
!ls -alh | grep model.h5

-rw-r--r-- 1 root root 243M Oct 24 07:44 model.h5


## Make predictions

In [0]:

#new_text = np.array(new_text, dtype=object)[:, np.newaxis]
with tf.Session() as session:
  K.set_session(session)
  session.run(tf.global_variables_initializer())
  session.run(tf.tables_initializer())
  model.load_weights('./model.h5')  
  predicts = model.predict(test_text, batch_size=32)

In [145]:
first = predicts[0]
max_d = -1000000
min_d = 1000000
max_i = 0
min_i = 0
for i in range(len(predicts) - 1):
  v = predicts[i]
  d = scipy.spatial.distance.cosine(v, first)
  if max_d < d:
    max_d = d
    max_i = i
  if min_d > d:
    min_d = d
    min_i = i
print("Min and max distances: {0} and {1}".format(min_d, max_d))

Min and max distances: -4.907563178058183e-08 and 2.8883001750745763e-05


In [146]:
syll_mgr.interpret2(predicts[max_i])
for i in range(10):
  print(test_text[i])
  print(predicts[i])
  syll_mgr.interpret2(predicts[i])

[1429, 1293, 695, 1259, 128, 443, 997, 988, 187, 852]
['F R AO D', 'HH Y UW N', 'K Y UW B', 'K OW P', 'AH L', 'B EH L', 'Y AH NG', 'L IH SH', 'K L EY M', 'F AO R S']
['To life, the creamy onyx and the skins']
[0.48644406 0.4891513  0.48640507 ... 0.48797417 0.48611757 0.48469386]
[1114, 1293, 1296, 431, 963, 645, 1034, 969, 570, 1200]
['OW TH', 'HH Y UW N', 'F Y UH', 'S T UW P', 'M AH T', 'G OW L', 'F AO R M', 'JH ER', 'V AH N', 'D EH V']
['And what is Man the while? And what his will?']
[0.49001873 0.49415073 0.48510784 ... 0.49021637 0.48950568 0.48458475]
[195, 313, 857, 774, 176, 860, 325, 618, 234, 237]
['R IH', 'Z AY N', 'G R AE S', 'L IH NG Z', 'M ER Z', 'G AE', 'T IH D', 'S K W EH R', 'V EH N', 'P ER']
['Of startled grasses, and the hedge in bloom,--']
[0.48931998 0.49049613 0.4831991  ... 0.48727813 0.48540083 0.47938696]
[1114, 217, 1007, 1440, 963, 98, 1050, 969, 178, 748]
['OW TH', 'P R EH', 'K L AE', 'G EY Z', 'M AH T', 'ER Z', 'W AA', 'JH ER', 'S EH', 'L EY K S']
['The ma

In [147]:
categories = df_train.label.cat.categories.tolist()
predict_logits = predicts.argmax(axis=1)
print("Categorie: {0}".format(categories))
predict_labels = [categories[logit] for logit in predict_logits]
predict_labels

NameError: ignored

In [0]:

os.remove('./model.h5')