# [Keras + Universal Sentence Encoder = Deep Meter](https://www.dlology.com/blog/keras-meets-universal-sentence-encoder-transfer-learning-for-text-data/) 

This notebook creates an autoencoder using the Universal Sentence Encoder. The autoencoder output is CMUdict syllables. The dataset is that subset of Allison Parrish's Project Gutenberg poetry archive which happens to scan in iambic pentameter.

The notebook is based on Chengwei Zhang's example of wrapping the USE inside a larger tensorflow model saves to a Keras model (without save the USE itself in the TF model).

The Universal Sentence Encoder makes getting sentence level embeddings as easy as it has historically been to lookup the embeddings for individual words. The sentence embeddings can then be trivially used to compute sentence level meaning similarity as well as to enable better performance on downstream classification tasks using less supervised training data.

Since there are 10 one-hot values for 10 sets of 6k syllables, this is "multi-label classification"
Changes for multi-label classification:
sigmoid activation instead of softmax
binary_crossentropy

Text format is tab-separated, 2 columns: first text, second multi-level
array of syllables:


# Getting Started

This section sets up the environment for access to the Universal Sentence Encoder on TF Hub and provides examples of applying the encoder to words, sentences, and paragraphs.

In [1]:
# Install the latest Tensorflow version.
!pip3 install --quiet "tensorflow>=1.7"
# Install TF-Hub.
!pip3 install --quiet tensorflow-hub
%cd /content
!git clone https://github.com/LanceNorskog/deep_meter || true
%cd deep_meter
!git pull
# could not figure out how to read gzipped files as text!
!gunzip -qf blobs/*.gz || true
!gunzip -qf prepped_data/*.gz || true

/content
fatal: destination path 'deep_meter' already exists and is not an empty directory.
/content/deep_meter
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://github.com/LanceNorskog/deep_meter
   1125317..2061cc9  master     -> origin/master
Updating 1125317..2061cc9
Fast-forward
 syllables.py | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)
gzip: blobs/*.gz: No such file or directory
gzip: prepped_data/*.gz: No such file or directory


In [2]:
# boilerplate from base notebook
import tensorflow as tf
import tensorflow_hub as hub
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import re
import seaborn as sns
import keras.layers as layers
from keras.models import Model
from keras import backend as K
np.random.seed(10)

Using TensorFlow backend.


In [0]:
# github deep_meter code
import utils
# should not need this to use utils.flatten but is true anyway?
from itertools import chain
import subprocess
import syllables
# misc for this notebook
from ast import literal_eval

import scipy



In [0]:
module_url = "https://tfhub.dev/google/universal-sentence-encoder-large/3" #@param ["https://tfhub.dev/google/universal-sentence-encoder/2", "https://tfhub.dev/google/universal-sentence-encoder-large/3"]

In [5]:
# Import the Universal Sentence Encoder's TF Hub module
embed = hub.Module(module_url)
embed_size = embed.get_output_info_dict()['default'].get_shape()[1].value

INFO:tensorflow:Using /tmp/tfhub_modules to cache modules.


In [0]:
#sentence_labels = utils.flatten([['AE N D'], ['S T AH', 'B ER N'], ['B R AE S'], ['AE N D'], ['T IH N'], ['AE N D'], ['S AA', 'L AH D'], ['G OW L D']])
#other_sentence = utils.flatten([['T UW'], ['M IY'], ['IH T'], ['F L OW Z'], ['AH'], ['S AH', 'L AH N'], ['S T R IY M'], ['AH V'], ['T EH R Z']])
#third_sentence = utils.flatten([['DH AH'], ['N OW', 'B AH L'], ['S IY', 'M AH N'], ['HH UW'], ['W IH TH', 'HH EH L D'], ['DH AH'], ['HH AE N D']])

In [0]:
# read classified poetry lines: text tab [['syll', 'la', 'ble'], ...]
# clip to only most common syllables with syllable manager
def get_data(filename, syll_mgr, num_symbols):
    lines = open(filename, 'r').read().splitlines()
    text_lines = []
    enc_array = []
    num_syllables = syll_mgr.get_size()
    for i in range(0, len(lines)):
      parts = lines[i].split("\t")
      label = utils.flatten(literal_eval(parts[1]))
      if len(label) != num_symbols:
        continue
      enc = np.zeros((num_symbols * syll_mgr.get_size()), dtype=np.int8)
      for i in range(num_symbols):
        enc[num_syllables * i + syll_mgr.get_encoding(label[i])] = 1
      text_lines.append([parts[0]])
      enc_array.append(enc)

    return (np.array(text_lines), np.array(enc_array))


In [0]:
# syllables in descending order of occurrence - 6k in gutenberg.iambic_pentameter, 15k total
# clamp to most common 100 syllables while debugging- use NCE to get all syllables or interesting number
# 98 + pause + wildcard
num_syllables = 1000 
num_syllables = 2000 
# iambic pentameter
num_symbols = 10
syll_mgr = syllables.syllables(num_syllables)

# slow
num_epochs = 30
adam_0001 = tf.train.AdamOptimizer(0.0000005)

In [0]:
(train_text, train_label) = get_data('prepped_data/gutenberg.iambic_pentameter.train', syll_mgr, num_symbols)
num_training = len(train_text)
train_text = train_text[0:10000]
train_label = train_label[0:10000]

(test_text, test_label) = get_data('prepped_data/gutenberg.iambic_pentameter.test', syll_mgr, num_symbols)
num_testing = len(test_text)


In [10]:

for i in range(2):
  print(train_text[i][0])
  print(train_label[i])
  syll_mgr.interpret2(train_label[i])

And stubborn brass, and tin, and solid gold;
[0 0 0 ... 0 0 0]
[7, 38, 343, 0, 7, 0, 7, 77, 78, 114]
['AE N D', 'S T AH', 'B ER N', '?', 'AE N D', '?', 'AE N D', 'S AA', 'L AH D', 'G OW L D']
To me, it flows a sullen stream of tears.
[0 0 0 ... 0 0 0]
[30, 59, 231, 0, 36, 175, 937, 0, 40, 977]
['T UW', 'M IY', 'IH T', '?', 'AH', 'S AH', 'L AH N', '?', 'AH V', 'T EH R Z']


In [11]:
messages = []
for i in range(200):
  messages.append(train_text[i][0])
with tf.Session() as session:
  session.run([tf.global_variables_initializer(), tf.tables_initializer()])
  message_embeddings = session.run(embed(messages))
predicts = message_embeddings

INFO:tensorflow:Saver not created because there are no variables in the graph to restore


In [12]:
predicts = message_embeddings
print(len(predicts))
first = predicts[0]
for i in range(len(predicts) - 1):
  v = predicts[i]
  #print(scipy.spatial.distance.cosine(v, first))

200


## Wrap embed module in a Lambda layer
Explicitly cast the input as a string

In [0]:
def UniversalEmbedding(x):
    return embed(tf.squeeze(tf.cast(x, tf.string)), signature="default", as_dict=True)["default"]


## Assemble model

In [14]:
input_text = layers.Input(shape=(1,), dtype=tf.string)
embedding = layers.Lambda(UniversalEmbedding, output_shape=(embed_size,))(input_text)
dense = layers.Dense(256, activation='sigmoid')(embedding)
dense = layers.Dense(512, activation='sigmoid')(dense)
pred = layers.Dense(num_syllables * num_symbols, activation='sigmoid')(dense)
model = Model(inputs=[input_text], outputs=pred)
model.compile(loss='binary_crossentropy', optimizer=adam_0001, metrics=['accuracy'])
model.summary()

INFO:tensorflow:Saver not created because there are no variables in the graph to restore
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 1)                 0         
_________________________________________________________________
lambda_1 (Lambda)            (None, 512)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 256)               131328    
_________________________________________________________________
dense_2 (Dense)              (None, 512)               131584    
_________________________________________________________________
dense_3 (Dense)              (None, 20000)             10260000  
Total params: 10,522,912
Trainable params: 10,522,912
Non-trainable params: 0
_________________________________________________________________


In [15]:
test_label.shape

(4200, 20000)

In [16]:
syll_mgr.interpret2(test_label[0])

[30, 530, 31, 4, 59, 1559, 0, 7, 31, 0]
['T UW', 'L AY F', 'DH AH', 'K R IY', 'M IY', 'AA', '?', 'AE N D', 'DH AH', '?']


## Train Keras model and save weights
This only train and save our Keras layers not the embed module' weights.

In [0]:
if not os.path.exists('./model.h5'):
  with tf.Session() as session:
    K.set_session(session)
    session.run(tf.global_variables_initializer())
    session.run(tf.tables_initializer())
    history = model.fit(train_text, 
            train_label,
            validation_data=(test_text, test_label),
            epochs=num_epochs,
            batch_size=32)
    model.save_weights('./model.h5')


In [19]:
!ls -alh | grep model.h5

-rw-r--r-- 1 root root  41M Oct 24 02:08 model.h5


## Make predictions

In [0]:

#new_text = np.array(new_text, dtype=object)[:, np.newaxis]
with tf.Session() as session:
  K.set_session(session)
  session.run(tf.global_variables_initializer())
  session.run(tf.tables_initializer())
  model.load_weights('./model.h5')  
  predicts = model.predict(test_text, batch_size=32)

In [0]:
first = predicts[0]
for i in range(len(predicts) - 1):
  v = predicts[i]
  #print(scipy.spatial.distance.cosine(v, first))

In [22]:
print(predicts.shape)
#print(str(predicts[0]))
#print(str(predicts[1]))
for i in range(10):
  print(test_text[i])
  print(predicts[i])
  print(syll_mgr.interpret2(predicts[i]))

(4200, 20000)
['To life, the creamy onyx and the skins']
[0.43416473 0.41284394 0.43051973 ... 0.4588917  0.46209702 0.5241755 ]
[1279, 1429, 662, 1731, 1838, 1980, 1163, 1657, 509, 1510]
['HH AO R', 'F R AO D', 'F IY L', 'K R AW N Z', 'V AY T S', 'B EY S', 'B L EH S T', 'CH EY S T', 'ER TH', 'S AO']
None
['And what is Man the while? And what his will?']
[0.4345424  0.41299087 0.43049657 ... 0.45883498 0.46186814 0.52442175]
[1279, 1429, 662, 1731, 1838, 1980, 1163, 1657, 509, 1510]
['HH AO R', 'F R AO D', 'F IY L', 'K R AW N Z', 'V AY T S', 'B EY S', 'B L EH S T', 'CH EY S T', 'ER TH', 'S AO']
None
['Of startled grasses, and the hedge in bloom,--']
[0.4345115  0.41287327 0.43034396 ... 0.4588948  0.46188018 0.5243139 ]
[1279, 1429, 662, 1731, 1838, 1980, 1163, 1657, 509, 1510]
['HH AO R', 'F R AO D', 'F IY L', 'K R AW N Z', 'V AY T S', 'B EY S', 'B L EH S T', 'CH EY S T', 'ER TH', 'S AO']
None
['The match was offered, the proposals made']
[0.43435743 0.41301456 0.43056476 ... 0.458796

In [52]:
categories = df_train.label.cat.categories.tolist()
predict_logits = predicts.argmax(axis=1)
print("Categorie: {0}".format(categories))
predict_labels = [categories[logit] for logit in predict_logits]
predict_labels

NameError: ignored

In [0]:
os.remove('./model.h5')